### ISSUE TITLE
left right icon not showing up

### ISSUE THREAD

**Issue by kpx-dev** [philipjkim/polymer-image-slider#5]
http://g.recordit.co/uLeVMlKENE.gif

Hi,
The dot loads fine for me at the bottom of the image but the icon doesn't show left and right arrow. 

I'm using:
    "polymer": "polymer/polymer#1.7.0",
    "polymer-image-slider": "^2.4.1"

Thanks.

**Comment by kpx-dev** [comment]
Looks like I need the iron-icons loaded: 
https://elements.polymer-project.org/elements/iron-icons

**Comment by philipjkim** [comment]
@kienpham2000 Thanks for openning the issue. I'll add iron-icons to dependencies.
