### ISSUE TITLE
Possible style change for responsive behaviour

### ISSUE THREAD

**Issue by gdevacc12** [philipjkim/polymer-image-slider#7]
I found making a style change to polymer-image-slider.html seems to give a better responsive behaviour. Changing: width from 1% to 100% for the outer class, i.e.:
.outer {
        width: 100%;
        display: table;
      }

As a side note, this component appears to work OK with Polymer 2.

**Comment by philipjkim** [comment]
Thanks for the tip! It'll be great if you make a PR for this, and I'll merge it ASAP.

**Comment by gdevacc12** [comment]
Thanks for the nice work Philip. PR created. Let me know if any problems.
